// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// maxprod
double maxprod(arma::mat X, arma::vec y, arma::uvec v, arma::vec m);
RcppExport SEXP _sparsevar_maxprod(SEXP XSEXP, SEXP ySEXP, SEXP vSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(maxprod(X, y, v, m));
    return rcpp_result_gen;
END_RCPP
}
// gLoss
double gLoss(arma::colvec r);
RcppExport SEXP _sparsevar_gLoss(SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(gLoss(r));
    return rcpp_result_gen;
END_RCPP
}
// crossprod
arma::colvec crossprod(arma::sp_mat X, arma::colvec y);
RcppExport SEXP _sparsevar_crossprod(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(crossprod(X, y));
    return rcpp_result_gen;
END_RCPP
}
// cdfit_gaussianTEST
Rcpp::List cdfit_gaussianTEST(arma::sp_mat X, arma::colvec Y, arma::colvec lambda, double eps, int max_iter, double gamma, arma::colvec multiplier, double alpha, int dfmax, int user);
RcppExport SEXP _sparsevar_cdfit_gaussianTEST(SEXP XSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP max_iterSEXP, SEXP gammaSEXP, SEXP multiplierSEXP, SEXP alphaSEXP, SEXP dfmaxSEXP, SEXP userSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type user(userSEXP);
    rcpp_result_gen = Rcpp::wrap(cdfit_gaussianTEST(X, Y, lambda, eps, max_iter, gamma, multiplier, alpha, dfmax, user));
    return rcpp_result_gen;
END_RCPP
}
// standardize2
Rcpp::List standardize2(arma::mat X);
RcppExport SEXP _sparsevar_standardize2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(standardize2(X));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP sparsevar_cdfit_gaussianTEST(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP sparsevar_crossprod(SEXP, SEXP);
RcppExport SEXP sparsevar_gLoss(SEXP);
RcppExport SEXP sparsevar_maxprod(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP sparsevar_standardize2(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_sparsevar_maxprod", (DL_FUNC) &_sparsevar_maxprod, 4},
    {"_sparsevar_gLoss", (DL_FUNC) &_sparsevar_gLoss, 1},
    {"_sparsevar_crossprod", (DL_FUNC) &_sparsevar_crossprod, 2},
    {"_sparsevar_cdfit_gaussianTEST", (DL_FUNC) &_sparsevar_cdfit_gaussianTEST, 10},
    {"_sparsevar_standardize2", (DL_FUNC) &_sparsevar_standardize2, 1},
    {"sparsevar_cdfit_gaussianTEST", (DL_FUNC) &sparsevar_cdfit_gaussianTEST, 10},
    {"sparsevar_crossprod",          (DL_FUNC) &sparsevar_crossprod,           2},
    {"sparsevar_gLoss",              (DL_FUNC) &sparsevar_gLoss,               1},
    {"sparsevar_maxprod",            (DL_FUNC) &sparsevar_maxprod,             4},
    {"sparsevar_standardize2",       (DL_FUNC) &sparsevar_standardize2,        1},
    {NULL, NULL, 0}
};

RcppExport void R_init_sparsevar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
