// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// maxprod
double maxprod(arma::mat X, arma::vec y, arma::uvec v, arma::vec m);
RcppExport SEXP sparsevar_maxprod(SEXP XSEXP, SEXP ySEXP, SEXP vSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    __result = Rcpp::wrap(maxprod(X, y, v, m));
    return __result;
END_RCPP
}
// gLoss
double gLoss(arma::colvec r);
RcppExport SEXP sparsevar_gLoss(SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::colvec >::type r(rSEXP);
    __result = Rcpp::wrap(gLoss(r));
    return __result;
END_RCPP
}
// crossprod
arma::colvec crossprod(arma::sp_mat X, arma::colvec y);
RcppExport SEXP sparsevar_crossprod(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    __result = Rcpp::wrap(crossprod(X, y));
    return __result;
END_RCPP
}
// cdfit_gaussianTEST
Rcpp::List cdfit_gaussianTEST(arma::sp_mat X, arma::colvec Y, arma::colvec lambda, double eps, int max_iter, double gamma, arma::colvec multiplier, double alpha, int dfmax, int user);
RcppExport SEXP sparsevar_cdfit_gaussianTEST(SEXP XSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP max_iterSEXP, SEXP gammaSEXP, SEXP multiplierSEXP, SEXP alphaSEXP, SEXP dfmaxSEXP, SEXP userSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< int >::type user(userSEXP);
    __result = Rcpp::wrap(cdfit_gaussianTEST(X, Y, lambda, eps, max_iter, gamma, multiplier, alpha, dfmax, user));
    return __result;
END_RCPP
}
// standardize2
Rcpp::List standardize2(arma::mat X);
RcppExport SEXP sparsevar_standardize2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    __result = Rcpp::wrap(standardize2(X));
    return __result;
END_RCPP
}
