// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gLoss
double gLoss(NumericVector r, int n);
RcppExport SEXP sparsevar_gLoss(SEXP rSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(gLoss(r, n));
    return __result;
END_RCPP
}
// tp
arma::sp_mat tp(const arma::sp_mat X, const arma::sp_mat Y);
RcppExport SEXP sparsevar_tp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat >::type Y(YSEXP);
    __result = Rcpp::wrap(tp(X, Y));
    return __result;
END_RCPP
}
