# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

maxprod <- function(X, y, v, m) {
    .Call('sparsevar_maxprod', PACKAGE = 'sparsevar', X, y, v, m)
}

gLoss <- function(r) {
    .Call('sparsevar_gLoss', PACKAGE = 'sparsevar', r)
}

crossprod <- function(X, y) {
    .Call('sparsevar_crossprod', PACKAGE = 'sparsevar', X, y)
}

cdfit_gaussianTEST <- function(X, Y, lambda, eps, max_iter, gamma, multiplier, alpha, dfmax, user) {
    .Call('sparsevar_cdfit_gaussianTEST', PACKAGE = 'sparsevar', X, Y, lambda, eps, max_iter, gamma, multiplier, alpha, dfmax, user)
}

standardize2 <- function(X) {
    .Call('sparsevar_standardize2', PACKAGE = 'sparsevar', X)
}

