# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gLoss <- function(r, n) {
    .Call('sparsevar_gLoss', PACKAGE = 'sparsevar', r, n)
}

tp <- function(X, Y) {
    .Call('sparsevar_tp', PACKAGE = 'sparsevar', X, Y)
}

cdfit_gaussian <- function() {
    .Call('sparsevar_cdfit_gaussian', PACKAGE = 'sparsevar')
}

