# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gLoss <- function(r) {
    .Call('sparsevar_gLoss', PACKAGE = 'sparsevar', r)
}

crossprod <- function(X, y) {
    .Call('sparsevar_crossprod', PACKAGE = 'sparsevar', X, y)
}

tp <- function(X, Y) {
    .Call('sparsevar_tp', PACKAGE = 'sparsevar', X, Y)
}

cdfit_gaussian <- function(X, Y, lambda, eps, max_iter, gamma, multiplier, alpha, dfmax, user) {
    .Call('sparsevar_cdfit_gaussian', PACKAGE = 'sparsevar', X, Y, lambda, eps, max_iter, gamma, multiplier, alpha, dfmax, user)
}

